// This program is used to obtain the values in Table 5, namely the values of p_{T,k} for each four-vertex tournament T and each k=2,3,4,
// as well as p_{T_5,2}, p_{T_5,3}, p_{T_6,2}.

#include <iostream>

const int numTournaments[7] = { 1,1,1,2,4,12,56}; // numTournaments[r] is the number of tournaments on r vertices 
const int k = 3; // k-majority are considred (k=2,3,4 are valid)
const int r = 5; // the size of the tournaments under investigation

int rfact; // r! (for efficiency, defined explixcitly)

int perm[720][r];			    // represents all permutations on {0,..,r-1}
int graph[56][r][r];			// adjacency matrix of tournaments on r vertices
int maj[r][r];					// a tournament generated by a set of permutations
int generatorIndices[2*k-1];	// the indices of the three permutations that generate trhe current genGraph
long long densities[456];

int fact(int n) {
	int f = 1;
	for (int i = 2; i <= n; i++)
		f *= i;
	return f;
}

bool checkIsomorphic(int f) { // check if the tournament indexed f is isomorphic to the generated graph
	for (int p = 0; p < rfact; p++) {
		bool good = true;
		for (int k = 0; k < r && good; k++)
			for (int m = 0; m < r && good; m++)
				if (k != m && (graph[f][perm[p][k]][perm[p][m]] != maj[k][m]))
					good = false;
		if (good)
			return true;
	}
	return false;
}

void loadPerm() {
	FILE* permfile;
	char fileName[100];
	sprintf_s(fileName, "d:\\research\\general\\combinatorial data\\permutations%d.txt", r); // a file containing all permutations of [r], one in each line
	fopen_s(&permfile, fileName, "r");
	for (int i = 0; i < rfact; i++) {
		for (int j = 0; j < r; j++) {
			char c;
			fscanf_s(permfile, "%c", &c);
			perm[i][j] = c - '1';
		}
		fgetc(permfile);
	}
	fclose(permfile);
}

void loadTours() {
	FILE* tourFile;
	char fileName[100];

	sprintf_s(fileName, "d:\\research\\general\\combinatorial data\\tour%d.txt", r); // a file containing the adjacency information for each tournament on r vertices
	fopen_s(&tourFile, fileName, "r");
	for (int i = 0; i < numTournaments[r]; i++) {
		for (int j = 0; j < r; j++) {
			graph[i][j][j] = 0;
			for (int k = j + 1; k < r; k++) {
				char c = fgetc(tourFile);
				c == '0' ? graph[i][j][k] = 0 : graph[i][j][k] = 1;
				graph[i][k][j] = 1 - graph[i][j][k];
			}
		}
		fgetc(tourFile);
	}
	fclose(tourFile);
}

void createMaj() {
	for (int i = 0; i < r; i++)
		for (int j = i + 1; j < r; j++) {
			int count = 0;
			for (int s = 0; s < 2 * k - 1; s++)
				if (perm[generatorIndices[s]][i] < perm[generatorIndices[s]][j])
					count++;
			maj[i][j] = count >= k ? 1 : 0;
			maj[j][i] = 1 - maj[i][j];
		}
}

int indIsomorph() {
	for (int f = 0; f < numTournaments[r]; f++)
		if (checkIsomorphic(f))
			return f;
}

void printPermutation(int p) { // p is the serial number of the permutation
	int reverse[r];
	for (int i = 0; i < r; i++)
		reverse[perm[p][i]] = i;
	for (int i = 0; i < r; i++)
		printf("%d", reverse[i]);
	printf("\n");
}

void main() {
	rfact = fact(r);
	loadPerm();
	loadTours();
	if (k == 2) {
		generatorIndices[0] = 0;
		// loop through all (r!)^3 possible triples of permutatons. Construct the majority tournament for each triple, and see which tournament it induces
		for (int i = 0; i < rfact; i++) {
			generatorIndices[1] = i;
			for (int j = 0; j < rfact; j++) {
				generatorIndices[2] = j;
				createMaj();
				densities[indIsomorph()]++;
			}
		}
		for (int i = 0; i < numTournaments[r]; i++)
			printf("density of tournament %d is %lld/%lld=%f\n", i, densities[i] * rfact , (long long)rfact * rfact * rfact, (double)rfact * densities[i]/(double)((double)rfact * rfact * rfact));
	}
	if (k == 3) {
		// loop through all (r!)^5 possible triples of permutatons. Construct the majority tournament for each triple, and see which tournament it induces
		generatorIndices[0] = 0;
		for (int i = 0; i < rfact; i++) {
			generatorIndices[1] = i;
			for (int j = 0; j < rfact; j++) {
				generatorIndices[2] = j;
				for (int k = 0; k < rfact; k++) {
					generatorIndices[3] = k;
					for (int l = 0; l < rfact; l++) {
						generatorIndices[4] = l;
						createMaj();
						densities[indIsomorph()]++;
					}
				}
			}
		}
		for (int i = 0; i < numTournaments[r]; i++)
			printf("density of tournament %d is %lld/%lld=%f\n", i, densities[i] * rfact, (long long)rfact * rfact * rfact * rfact * rfact, (double)rfact*densities[i] / (double)((double)rfact * rfact * rfact * rfact * rfact));
	}
	if (k == 4) {
		generatorIndices[0] = 0;
		for (int i = 0; i < rfact; i++) {
			generatorIndices[1] = i;
			for (int j = 0; j < rfact; j++) {
				generatorIndices[2] = j;
				for (int k = 0; k < rfact; k++) {
					generatorIndices[3] = k;
					for (int l = 0; l < rfact; l++) {
						generatorIndices[4] = l;
						for (int m = 0; m < rfact; m++) {
							generatorIndices[5] = m;
							for (int s = 0; s < rfact; s++) {
								generatorIndices[6] = s;
								createMaj();
								densities[indIsomorph()]++;
							}
						}
					}
				}
			}
		}
		for (int i = 0; i < numTournaments[r]; i++)
			printf("density of tournament %d is %lld/%lld=%f\n", i, densities[i] * rfact, (long long)rfact * rfact * rfact * rfact * rfact * rfact * rfact, (double)(rfact * densities[i]) / (double)((double)rfact * rfact * rfact * rfact * rfact * rfact * rfact));
	}
}