// This program searches for (2,4)-impartial culture generating sets of size 12.

#include <iostream>

int perm[24][4];								// represents all permutations on {0,1,2,3}
int graph[4][4][4];								// adjacency matrix of all four tournaments on 4 vertices
int maj[4][4];									// a graph generated by a set of permutations
int generatorIndices[3];						// the indices of the three permutations that generate the current tournament "maj"
long long densities[4];

int generatorSetIndices[12];

bool checkIsomorphic(int f) { // check if the tournament indexed f is isomorphic to the generated graph
	for (int p = 0; p < 24; p++) {
		bool good = true;
		for (int k = 0; k < 4 && good; k++)
			for (int m = 0; m < 4 && good; m++)
				if (k != m && (graph[f][perm[p][k]][perm[p][m]] != maj[k][m]))
					good = false;
		if (good)
			return true;
	}
	return false;
}

void loadPerm() {
	FILE* permfile;
	char fileName[100];
	sprintf_s(fileName, "d:\\research\\general\\combinatorial data\\permutations4.txt"); // a 24-line file with a permutation of {0,1,2,3} in every line
	fopen_s(&permfile, fileName, "r");
	for (int i = 0; i < 24; i++) {
		for (int j = 0; j < 4; j++) {
			char c;
			fscanf_s(permfile, "%c", &c);
			perm[i][j] = c - '1';
		}
		fgetc(permfile);
	}
	fclose(permfile);
}

void loadTours() {
	FILE* tourFile;
	char fileName[100];

	sprintf_s(fileName, "d:\\research\\general\\combinatorial data\\tour4.txt"); // a file containing the adjacency matrix of each tournament on four vertices
	fopen_s(&tourFile, fileName, "r");
	for (int i = 0; i < 4; i++) {
		for (int j = 0; j < 4; j++) {
			graph[i][j][j] = 0;
			for (int k = j + 1; k < 4; k++) {
				char c = fgetc(tourFile);
				c == '0' ? graph[i][j][k] = 0 : graph[i][j][k] = 1;
				graph[i][k][j] = 1 - graph[i][j][k];
			}
		}
		fgetc(tourFile);
	}
	fclose(tourFile);
}

void createMaj() {
	for (int i = 0; i < 4; i++)
		for (int j = i + 1; j < 4; j++) {
			int count = 0;
			for (int s = 0; s < 3; s++)
				if (perm[generatorIndices[s]][i] < perm[generatorIndices[s]][j])
					count++;
			maj[i][j] = count >= 2 ? 1 : 0;
			maj[j][i] = 1 - maj[i][j];
		}
}

int indIsomorph() {
	for (int f = 0; f < 4; f++)
		if (checkIsomorphic(f))
			return f;
}

void printPermutation(int p) { // p is the serial number of the permutation
	int reverse[4];
	for (int i = 0; i < 4; i++)
		reverse[perm[p][i]] = i;
	for (int i = 0; i < 4; i++)
		printf("%d", reverse[i]);
	printf("\n");
}

void main() {
	loadPerm();
	loadTours();
	for (int t = 0; t < 16777216; t++) {
		int s = t;
		int binary[24];
		for (int i = 0; i < 24; i++) {
			binary[i] = s % 2;
			s = s / 2;
		}
		int count = 0;
		for (int i = 0; i < 24; i++)
			if (binary[i] == 1)
				count++;
		if (count != 12)
			continue;
		count = 0;
		for (int i = 0; i < 24; i++)
			if (binary[i] == 1)
				generatorSetIndices[count++] = i;
		for (int i = 0; i < 4; i++)
			densities[i] = 0;
		for (int i = 0; i < 12; i++) {
			generatorIndices[0] = generatorSetIndices[i];
			for (int j = 0; j < 12; j++) {
				generatorIndices[1] = generatorSetIndices[j];
				for (int k = 0; k < 12; k++) {
					generatorIndices[2] = generatorSetIndices[k];
					createMaj();
					densities[indIsomorph()]++;
				}
			}
		}
		if (densities[0] == 1434 && densities[1] == 102 && densities[2] == 90) {
			for (int i = 0; i < 4; i++)
				printf("Generator density of tournament %d is %d/%d=%lf\n", i, densities[i], 12 * 12 * 12, densities[i] / (double)(12 * 12 * 12));
			for (int i = 0; i < 12; i++)
				printPermutation(generatorSetIndices[i]);
		}
	}
}